name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  IMAGE_NAME: "teastandtoastnextjs"

jobs:
  build-project:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install NPM dependencies
        run: npm install
      - name: Build
        run: npm run build

  docker-build-push:
      needs: build-project
      name: Build Docker
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4
        - name: Login to docker hub
          uses: docker/login-action@v2
          with:
            username: ${{secrets.DOCKER_HUB_USERNAME}}
            password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        -
          name: Build and push
          uses: docker/build-push-action@v3
          with:
            context: 
            file: ./Dockerfile
            push: true
            tags: ${{secrets.DOCKER_HUB_USERNAME}}/next-portfolio:0.1